theme = "hugo-material-theme"
languageCode = "en-us"
title = "Datasets"
publishDir = "docs"
baseurl = "/"
relativeurls = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  background = "https://cboettig.github.io/dataspice-web/img/bg7.jpg"
